networks:
  default:
    external: true
    name: roboshopnw
services:
  mongodb:
    image: mongodb:v1.0
    container_name: mongodb
    
  catalogue:
    image: catalogue:v1.0
    container_name: catalogue
    depends_on: 
      - mongodb
  web:
   image: web:v1.0
   container_name: web
   ports:
      - "80:80"
   depends_on: 
      - catalogue
      - cart
      - user
      - shipping
      - payment
  redis:
    image: redis
    
  user:
    image: user:v1.0
    container_name: user
    depends_on: 
      - redis
      - mongodb
      - cart
  cart:
    image: cart:v1.0
    container_name: cart
    depends_on: 
      - redis
      - catalogue
  mysql:
    image: mysql:v1.0
    container_name: mysql
  shipping:
     image: shipping:v1.0
     container_name: shipping
     depends_on: 
      - mysql
      - cart
  Rabbitmq:
       image: rabbitmq
       environment: 
       - RABBITMQ_DEFAULT_USER=roboshop \
       - RABBITMQ_DEFAULT_PASS=roboshop123 \
  payment:
       image: payment:v1.0
       container_name: payment
       depends_on: 
       - Rabbitmq

      